server:
  port: 0
  servlet:
    context-path: /auth-service
spring:
  application:
    name: auth-service
  config:
    import: configserver:http://localhost:8888

# service registry
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka