server:
  port: 0
  servlet:
    context-path: /redis-demo
spring:
  application:
    name: redis-demo
  redis:
    host: localhost
    port: 6379

# service registry
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#  cache constants
cache:
  config:
    entryTtl: 60
    countryNames:
      entryTtl: 30