server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          products-client-client-credentials:
            provider: spring
            client-id: products-client
            client-secret: secret
            authorization-grant-type: client_credentials
            client-name: products-client-client-credentials
            scope: products.read
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000
  mvc:
    log-request-details: true
  codec:
    log-request-details: true


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTemplate: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG