server:
  port: 0
  servlet:
    context-path: /order-service
spring:
  application:
    name: order-service
  # config server
  config:
    import: configserver:http://localhost:8888

# service registry
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# observability
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  tracing:
    sampling:
      probability: 1.0