server:
  port: 0

spring:
  application:
    name: consumer
  kafka:
    bootstrap-servers: ${app.kafka.bootstrapServers}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-class: java.lang.String
      value-class: java.lang.String
app:
  kafka:
    bootstrapServers: localhost:9092
    topics:
      inbound:
        example: KAFKA_EXAMPLE
        events: KAFKA_EVENTS_EXAMPLE
      streams:
        input: topic_a
        output: topic_b
    retry:
      initialInterval: 1
      multiplier: 3