global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8888' ] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'inventory-service'
    metrics_path: '/inventory-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'order-service'
    metrics_path: '/order-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'payment-service'
    metrics_path: '/payment-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'rating-service'
    metrics_path: '/rating-service/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'product-service'
    metrics_path: '/product-service/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ] ## only for demo purposes don't use host.docker.internal in production
